project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    #- schedule.qmd
    #- projects.qmd
    - 01_command_shells.qmd
    - 02_python_environments.qmd
    - 03_git_github.qmd
    - 04_scc.qmd
    - 05_scc_cont.qmd
    - 06_scc_batch_computing.qmd
    #- 10-pytorch-01.qmd
    #- 12-pytorch-02-dataloaders.qmd
    #- 13-pytorch-03-model-def.qmd
    #- 14-pytorch-04-autograd.qmd
    #- 15-pytorch-05-training.qmd
    #- 16-lc01-simple-llm-app.qmd
    #- 17-lc02-chatbot.qmd
    #- 18-lc03-retrievers.qmd
    #- 19-lc04-agent.qmd
execute: 
  freeze: auto
  # cache: true

resources:
  - src/langchain/requirements.txt
  - src/langchain/02-langchain-chatbot.ipynb
  - src/langchain/03-retrievers.ipynb
  - src/langchain/04-agents.ipynb


website:
  title: "Shell, SCC and Python Tips and Tricks"
  back-to-top-navigation: true
  favicon: "assets/images/spark-logo.png"
  page-footer: "Shell, SCC and Python Tips"
  navbar:
    background: "primary"
    tools:
    - icon: github
      menu: 
      - text: Source Code
        href: https://github.com/trgardos/shell-scc-python
      - text: Report a Bug
        href: https://github.com/trgardos/shell-scc-python/issues
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      #- href: schedule.qmd
      #- href: projects.qmd
      - section: "Notes"
        contents:
          - href: 01_command_shells.qmd
            text: 01 -- Command Shells
          - href: 02_python_environments.qmd
            text: 02 -- Python Environments
          - href: 03_git_github.qmd
            text: 03 -- Git and GitHub
          - href: 04_scc.qmd
            text: 04 -- Shared Computing Cluster
          - href: 05_scc_cont.qmd
            text: 05 -- SCC Continued
          - href: 06_scc_batch_computing.qmd
            text: 06 -- SCC Batch Computing
          #- href: 10-pytorch-01.qmd
          #  text: 10 -- PyTorch 01 - Intro and Tensors
          #- href: 12-pytorch-02-dataloaders.qmd
          #  text: 12 -- PyTorch 02 - Dataloaders and Transforms
          #- href: 13-pytorch-03-model-def.qmd
          #  text: 13 -- PyTorch 03 - Model Definition
          #- href: 14-pytorch-04-autograd.qmd
          #  text: 14 -- PyTorch 04 - Autograd
          #- href: 15-pytorch-05-training.qmd
          #  text: 15 -- PyTorch 05 - Training and Evaluation
          #- href: 16-lc01-simple-llm-app.qmd
          #  text: 16 -- LangChain 01 - Building a Simple LLM App with LangChain
          #- href: 17-lc02-chatbot.qmd
          #  text: 17 -- LangChain 02 - Build a Chatbot with LangChain
          #- href: 18-lc03-retrievers.qmd
          #  text: 18 -- LangChain 03 - Embeddings, Vector Stores and Retrievers
          #- href: 19-lc04-agent.qmd
          #  text: 19 -- LangChain 04 - Build an Agent

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    code-fold: false
