project:
  output-dir: _revealjs
  render:
    - 01_command_shells.qmd
    - 02_python_environments.qmd
    - 03_git_github.qmd
    - 04_scc.qmd
    - 05_scc_cont.qmd
    - 06_scc_batch_computing.qmd
    #- 10-pytorch-01.qmd
    #- 11-pytorch-02-dataloaders.qmd
format:
  revealjs:
    footer: "Gardos"
    scrollable: true
    slide-number: c/t
    show-slide-number: all
    chalkboard: true
    smaller: true
    html-math-method: mathjax
    echo: true
    code-fold: false
